services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - dgraph
    environment:
      - DGRAPH_URL=http://dgraph:8080/graphql
    command: >
      sh -c "
      until curl -s http://dgraph:8080/health | grep -q '\"status\":\"healthy\"'; do
          echo 'Waiting for Dgraph to be ready...';
          sleep 3;
        done;
      echo 'Dgraph is ready. Attempting to post schema...';
      until curl -s -X POST http://dgraph:8080/admin/schema --data-binary '@/app/db-schema.graphql' | grep -q -v '\"message\":\"Unavailable: Server not ready.\"'; do
          echo 'Schema post failed. Retrying...';
          sleep 3;
        done;
      echo 'Schema posted successfully.';
      npm start
      "

  dgraph:
    image: dgraph/standalone:v21.03.2
    ports:
      - "8080:8080"
      - "9080:9080"
      - "8000:8000"
    volumes:
      - dgraph-data:/dgraph

volumes:
  dgraph-data:

